### ISSUE TITLE
Messages don't appear when ParleyView is added before configuring Parley.State

### ISSUE THREAD

**Issue by Nienke0905** [parley-messaging/ios-library#195]
Describe the Bug
With the update of Parley  4.2.5, when ParleyView is added before Parley.State is configured the messages do not appear when Parley is configured

To Reproduce
- In the package, replace `IdentifierViewController` with the content of the attached (change is that the `performSegue` is called prior to configuring Parley, and `kOfflineMessagingEnabled` is false)
- Start the sample app
- Open the chat and send some messages
- Press done
- Open the chat again

Observed behaviour:
- No previous messages are being shown

Expected behaviour:
- Previously send messages are shown

[IdentifierViewController.txt](https://github.com/user-attachments/files/19367674/IdentifierViewController.txt)

**Comment by alexkok** [comment]
Fixed in [4.2.6](https://github.com/parley-messaging/ios-library/releases/tag/4.2.6) 🚀

**Comment by Nienke0905** [comment]
Hi @alexkok,

I believe it is not fixed. When the view is loaded before the API call is done, the messages are still not displayed. If you replace the `IdentifierViewController` with the content of the file attached you will see the bug.

[IdentifierViewControllerDispatch.txt](https://github.com/user-attachments/files/19482977/IdentifierViewControllerDispatch.txt)

FYI, if you change the `Dispathqueue.main` to `Dispatchqueue.global()` in the above file the app will crash after 2 seconds.

**Comment by alexkok** [comment]
Woops, sorry @Nienke0905 , thanks for reporting again!

Now fixed properly in [4.2.7](https://github.com/parley-messaging/ios-library/releases/tag/4.2.7) 🚀 

(the configure from background issue should be solved as well)

**Comment by Nienke0905** [comment]
Hi @alexkok,

I'm afraid this still hasn't fully solved the problem.
Yes, previously send messages are now displayed correctly. 🎉 But newly send messages are only shown when you first navigate back again. 

If you replace the IdentifierViewController with the content of the file attached you will see the bug (same IdentifierViewController as last time).

https://github.com/user-attachments/assets/3e1e06e3-17ab-40ef-9d8b-5df670ea250e

**Comment by alexkok** [comment]
Thanks @Nienke0905 , another cause found with this indeed. Sorry for the inconvenience.

Can you test again with this version? Let me know.
Should be fixed now [4.2.8](https://github.com/parley-messaging/ios-library/releases/tag/4.2.8) 🚀
