### ISSUE TITLE
Messages not appearing on subsequent entry to Chat View

### ISSUE THREAD

**Issue by Nienke0905** [parley-messaging/ios-library#219]
We are unable to update to Parley 4.3.0 or 4.4.0 due to the following reason:
1. The user navigates to the Chat view the first time and older messages appear correctly
2. The user navigates away from the chat (e.g. back)
3. The user navigates to the Chat view again, but no older messages are appearing (an empty chat is displayed)

We see that the example app is configured differently from our app, mainly due to the `IdentifierViewController` where the secret is supplied instead of requested from a backend asynchronously when navigating to the Chat like in our situation.

We recreated the issue in the example app by changing the following:
1. Set openChatDirectly = true
2. startButton.setLoading(true) removed
3. Getting the secret asynchronously in the viewDidLoad of the ChatViewController
4. Set empty string on setUserInformation (we were told that we had to do this to start the SDK, but that backend will set the value)

[ios-library-4.4.0.zip](https://github.com/user-attachments/files/21579657/ios-library-4.4.0.zip)

**Comment by martijnvdwal** [comment]
Hi Nienke,

Thanks for explaining so thoroughly and providing the project! We should have a fix available soon.

**Comment by alexkok** [comment]
Hi @Nienke0905 , thanks for responding. It looks like you're using the library wrongly though, which causes this side effect. This is not the intended usage.

Note, that as stated in the REAMDE, calling `configure` multiple times is unsupported. But this is essentially what is being done here: Every time of opening the chat, the configure method is called. Even when Parley is already initialized, that is not what we would expect.

Once Parley is configured, the configure method should not be called anymore. Except if the reset method is called, only then yes, configure must be called again.

Now, in your example:
 
- The ParleyView is opened.
- `configure` is being called, chat loads in.
- We close the screen and chat (but not resetting Parley or so).
- We open the ParleyView again (this shows the chat again in the current state, correct).
- Now `configure` is called again -- But this isn't expected. Parley was already configured!

So to fix this, adjust to one of the following please:

1. Don't call configure again if Parley was already configured (this is what I would recommend).
2. Call reset (or purgeLocalMemory in your case) when closing the chat, then the next time the chat loads empty, and using configure should work neatly again. But this is less ideal, as you would reconfigure it every time when opening the chat.

_Sidenote: You are calling setUserInformation with an empty string, which essentially causes anonymous chats, I think that's not really intended? Or is your backend catching that and adding the userauthorization details there? (Not sure what goes on there, but looks strange)._

**Comment by Nienke0905** [comment]
Hi Alex,

Thank you for your suggestion that we always have to call reset.
Unfortunately that doesn't fix the issue though.

We noticed that the issue is showing up when there is a longer chat history that spans multiple days and many messages.
The attached video is made with Parley's sample app without any changes made to it by us. As you can, you scoll upwards to see older messages and then suddenly you are brought down again.

https://github.com/user-attachments/assets/59d34d59-bd1a-4972-8bba-6f41771bd837

In our app, chat histories can span several months. The app automatically scrolls the user down as in the video, but when you return to the chat screen a second time, the call to load additional messages is not triggered again, preventing you from viewing messages older than that point.
